apiVersion: apps/v1
kind: Deployment
metadata:
  name: rms-frontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rms-frontend
  template:
    metadata:
      labels:
        app: rms-frontend
    spec:
      containers:
      - name: rms-frontend
        image: kkukku0218/rms-frontend:c4567a489ff5afb9d6f0fb2c7dab7e3ce222f029
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: rms-frontend-service
spec:
  type: NodePort
  selector:
    app: rms-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31001 # 브라우저 접속용 포트 (GCP 방화벽 확인!)